Feat/ev 908/movimentation page
natycanellas/everest-crypto-wallet pull request #9
Opened 2022-10-11 19:42 UTC by natycanellas

## Link da Tarefa
[Tela de movimentações](https://warren.atlassian.net/jira/software/c/projects/EV/boards/454?modal=detail&selectedIssue=EV-908&assignee=6319e3b9b433b060db5757d5)

## Descrição
Construção da tela de movimentações com base no histórico de conversões de moedas realizadas pelo usuário.

- [x] Lista dinâmica e scrollable.
- [x] Dados da lista correspondendo a ação da tela de conversão.
- [x] Extra de detalhamento da operação (comprovante).

<img src="https://user-images.githubusercontent.com/113135440/195183739-b632cc0a-b387-4e98-a774-ed20a2531fcd.gif" width="250"/>

2022-10-11 19:55 UTC, julialuciani approved these changes

2022-10-11 19:55 UTC, julialuciani commented on lib/movimentations/widgets/divider_bottom_sheet_detail.dart
> +  Widget build(BuildContext context) {
Nem sempre faz sentido extrair um widget. No caso do divider a extração dele ocupa mais espaço do que fazer ele no Body e tirar a última vírgula para que só ocupe uma linha.

2022-10-11 19:55 UTC, julialuciani commented on lib/movimentations/widgets/column_coin_detail.dart
> +import 'package:flutter/material.dart';
Poderia ser a extração de uma row que recebe dois text e tem como parâmetros Strings, isso faria com que o arquivo fosse bem menor

2022-10-13 16:37 UTC, carloscasanovad approved these changes

2022-10-13 16:37 UTC, carloscasanovad commented on lib/shared/routes/routes.dart
> +  SuccessPage.route: (context) => const SuccessPage(),
Sugestão: Talvez depois você pode considerar em utilizar o onGenerate routes como a recomendação que o Carlos passou no grupo:
https://warreninvest.slack.com/archives/C041N86A09F/p1663676774341449

2022-10-14 12:35 UTC, CarlosTSIlva requested changes

2022-10-14 12:35 UTC, CarlosTSIlva commented on lib/main.dart
> +        initialRoute: '/crypto-page',
as rotas n estão definida na classe?
 Faz algo como CrptoPage.routes... porque se mudar la obrigatoriamente vai mudar aqui assim evitando códigos duplicados e manutenção mais facil

2022-10-14 12:35 UTC, CarlosTSIlva commented
quando corrigir da um alo

2022-10-14 13:01 UTC, CarlosTSIlva approved these changes

2022-10-14 13:03 UTC, merged